#!/bin/bash
# FT 데일리 브리핑 - 배포 스크립트 (GitHub 가이드)

echo "=========================================="
echo "🚀 FT 데일리 브리핑 배포 가이드"
echo "=========================================="
echo ""
echo "✅ 완료된 항목:"
echo "  [✓] 프로젝트 초기화"
echo "  [✓] 의존성 설정 (requirements.txt)"
echo "  [✓] 환경변수 설정 (.env)"
echo "  [✓] 모든 모듈 생성"
echo "  [✓] 단위 테스트 통과"
echo ""
echo "=========================================="
echo "🔧 다음 단계 (2가지 방법)"
echo "=========================================="
echo ""
echo "[방법 A] GitHub Web UI (추천 - 가장 간단)"
echo "=========================================="
echo ""
echo "1️⃣  GitHub 저장소 생성"
echo "   https://github.com/new"
echo "   ├─ Repository name: forbetterday"
echo "   ├─ Description: FT Daily Brief Automation"
echo "   ├─ Visibility: Public (또는 Private)"
echo "   └─ 'Create repository' 클릭"
echo ""
echo "2️⃣  로컬에서 Git 초기화 (Terminal에서)"
echo "   cd /Users/gangseong-gu/Desktop/forbetterday"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit: FT Daily Brief Automation'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/YOUR-USERNAME/forbetterday.git"
echo "   git push -u origin main"
echo ""
echo "3️⃣  GitHub Secrets 설정 (Web UI)"
echo "   저장소 → Settings → Security → Secrets and variables → Actions"
echo "   ├─ Secret 이름: CLAUDE_API_KEY"
echo "   │  값: sk-ant-v1-xxxxx... (Anthropic 콘솔에서 복사)"
echo "   ├─ Secret 이름: GMAIL_ADDRESS"
echo "   │  값: forbetterday@gmail.com"
echo "   └─ Secret 이름: GMAIL_PASSWORD"
echo "      값: xxxx xxxx xxxx xxxx (Gmail App Password)"
echo ""
echo "4️⃣  GitHub Actions 확인"
echo "   저장소 → Actions → 'FT 데일리 브리핑 자동화' 워크플로우 확인"
echo "   └─ 자동으로 매일 KST 08:00에 실행 (또는 수동 'Run workflow' 클릭)"
echo ""
echo ""
echo "[방법 B] GitHub CLI (명령어 선호)"
echo "=========================================="
echo ""
echo "$ brew install gh"
echo "$ gh auth login"
echo "$ gh repo create forbetterday --public --source=. --remote=origin --push"
echo ""
echo ""
echo "=========================================="
echo "📋 배포 체크리스트"
echo "=========================================="
echo ""
echo "□ (1) GitHub 계정 확인 (github.com 로그인)"
echo "□ (2) 새 저장소 'forbetterday' 생성"
echo "□ (3) Git 초기화 & Push"
echo "□ (4) GitHub Secrets 설정 (CLAUDE_API_KEY, GMAIL_ADDRESS, GMAIL_PASSWORD)"
echo "□ (5) GitHub Actions 워크플로우 활성화 확인"
echo ""
echo "=========================================="
echo "✨ 완료!"
echo "=========================================="
echo ""
echo "✅ 배포 완료 후:"
echo "  • 매일 KST 08:00 자동으로 실행됨"
echo "  • Gmail (forbetterday@gmail.com)로 이메일 수신"
echo "  • GitHub Actions 탭에서 실행 로그 확인 가능"
echo "  • output/ 폴더에 로그 저장"
echo ""
